### ISSUE TITLE
Builder crashes when installing nettle (Darwin, amd64, wine-1.7.27 staging)

### ISSUE THREAD

**Issue by alfadelta10010** [PhoenicisOrg/phoenicis-winebuild#146]
The error occurs while using the interactive builder. The same error occurs when I comment out the line `RUN VERSION="3.7.3" ARCH="i386" nettle.sh` and keep only `RUN VERSION="3.7.3" ARCH="x86_64" nettle.sh` in `environments/linux-amd64-wine_osxcross`. 

**Error output:**

```
Step 34/64 : RUN VERSION="3.7.3" ARCH="i386" nettle.sh
...
Searching for libraries
checking /opt/local/lib... not found
checking /usr/local/lib... added
checking /sw/local/lib... not found
checking /sw/lib... not found
checking /usr/gnu/lib... not found
checking /opt/gnu/lib... not found
checking /sw/gnu/lib... not found
checking /usr/freeware/lib... not found
checking /usr/pkg/lib... not found
checking for i386-apple-darwin17-gcc... i386-apple-darwin17-gcc
checking whether the C compiler works... no
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/containers.py", line 878, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/containers/create: Not Found ("No such image: phoenicis/winebuild/linux-amd64:wine_osxcross")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=wine_osxcross&fromImage=phoenicis%2Fwinebuild%2Flinux-amd64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 60, in build
    container.start()
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/core/Container.py", line 44, in start
    self.container = self.docker_client.client.containers.run(self.environment.full_name(), detach=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/containers.py", line 822, in run
    self.client.images.pull(image, platform=platform)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/images.py", line 444, in pull
    pull_log = self.client.api.pull(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/image.py", line 428, in pull
    self._raise_for_status(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=wine_osxcross&fromImage=phoenicis%2Fwinebuild%2Flinux-amd64: Not Found ("pull access denied for phoenicis/winebuild/linux-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
Cleaning container
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/containers.py", line 878, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/containers/create: Not Found ("No such image: phoenicis/winebuild/linux-amd64:wine_osxcross")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=wine_osxcross&fromImage=phoenicis%2Fwinebuild%2Flinux-amd64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 60, in build
    container.start()
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/core/Container.py", line 44, in start
    self.container = self.docker_client.client.containers.run(self.environment.full_name(), detach=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/containers.py", line 822, in run
    self.client.images.pull(image, platform=platform)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/models/images.py", line 444, in pull
    pull_log = self.client.api.pull(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/image.py", line 428, in pull
    self._raise_for_status(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=wine_osxcross&fromImage=phoenicis%2Fwinebuild%2Flinux-amd64: Not Found ("pull access denied for phoenicis/winebuild/linux-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/examples/interactive_builder.py", line 24, in <module>
    builder.build(distribution, version, os, arch)
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 70, in build
    container.clean()
  File "/Users/AbhuChinu/projects/phoenicis-winebuild/core/Container.py", line 151, in clean
    self.container.kill()
AttributeError: 'NoneType' object has no attribute 'kill'
```
(Apologies if this is the incorrect way of asking for guidance, I noticed other issues created with similar intent)

**Comment by Gcenx** [comment]
last time I’d worked on the Darwin environment it built just fine on May 18th https://github.com/PhoenicisOrg/phoenicis-winebuild/commit/73294779d387e2ceb21306dff9e6359e8a91c097

Sounds like this may be an issue with the SDK package you’ve used.

**Comment by alfadelta10010** [comment]
I'm supposed to use the SDK package from Xcode 9.4.1, MacOSX10.13.sdk, right? Got the folder from there.

**Comment by Gcenx** [comment]
You should instead follow https://github.com/tpoechtrager/osxcross#packaging-the-sdk-on-macos-xcode

Make sure the Xcode.app installed into /Application is Xcode v9.4.1 other Xcode9 versions have problems with there SDK

**Comment by alfadelta10010** [comment]
It worked, thank you so much :) 🙏

**Comment by Gcenx** [comment]
More an fwi you won’t be able to build below wine-2.18 due to changes in freetype2 that broken wine builds.

It’s possible the patch could be back-ported but honestly I don’t use anything so old anymore so not sure.

**Comment by Gcenx** [comment]
Here’s the relevant upstream commit https://source.winehq.org/git/wine.git/commit/40166848a7944383a4cfdaac9b18bd03fbb2b4f9

**Comment by Gcenx** [comment]
Updated the README to better explain packing the SDK.
